name = "apiforai"
main = "src/index.ts"
compatibility_date = "2025-03-01"

[[kv_namespaces]]
binding = "CACHE"
id = "74038fd2f6bb428bbe45109a82117602"

[triggers]
crons = ["0 * * * *"]

[vars]
# API keys configured via: wrangler secret put <KEY_NAME>
